const ERAS = [
  {
    "id": "era_1776908543422",
    "label": "Origins: the pre-pre-history of indie",
    "years": "? — 1976",
    "color": "#888888",
    "bg": "rgba(136,136,136,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776920202864",
    "label": "Pre-indie: Punk, Post-punk and New Wave",
    "years": "1976 — 1982",
    "color": "#ff4013",
    "bg": "rgba(255,64,19,0.1)",
    "desc": "A new chapter in the story"
  },
  {
    "id": "era_1776921668462",
    "label": "The Birth of Indie: How Hardcore and Jangle Pop Converged into C86",
    "years": "1982 — 1986",
    "color": "#002e7a",
    "bg": "rgba(0,46,122,0.1)",
    "desc": "",
    "dualColumn": true,
    "leftLabel": "🇺🇸",
    "rightLabel": "🇬🇧"
  },
  {
    "id": "era_1776921994953",
    "label": "Indie rock expands its sounds",
    "years": "1986 - 1991",
    "color": "#7b219f",
    "bg": "rgba(123,33,159,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776565376316",
    "label": "Summerbabe: The Extreme Long Tails of Slacker Rock",
    "years": "1991 — 1999",
    "color": "#d58400",
    "bg": "rgba(213,132,0,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776565014692",
    "label": "Chaos before the arrival of a new sound",
    "years": "1999 — 2001",
    "color": "#74a7fe",
    "bg": "rgba(116,167,254,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776471732213",
    "label": "Post-Punk Revival",
    "years": "2001 — 2003",
    "color": "#b51a00",
    "bg": "rgba(181,26,0,0.1)",
    "desc": "\"meet me in the bathroom.\""
  },
  {
    "id": "era_1776446456442",
    "label": "Folk Rock Goes Chamber",
    "years": "2003 — 2005",
    "color": "#669c35",
    "bg": "rgba(102,156,53,0.1)",
    "desc": "The sounds got softer but emotions became harder"
  },
  {
    "id": "sleaze",
    "label": "Indie Sleaze: Stage I",
    "years": "2006 – 2009",
    "color": "#00bd8d",
    "bg": "rgba(0,189,141,0.1)",
    "desc": "How indie rock became danceable"
  },
  {
    "id": "era_1776312948356",
    "label": "Indie Sleaze: Stage II",
    "years": "2009 - 2012",
    "color": "#f4a4c0",
    "bg": "rgba(244,164,192,0.1)",
    "desc": "Psychedelia and nostalgia",
    "dualColumn": false,
    "leftLabel": "",
    "rightLabel": ""
  },
  {
    "id": "era_1776922305893",
    "label": "Indie Poptimism",
    "years": "2012 — 2016",
    "color": "#b92d5d",
    "bg": "rgba(185,45,93,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776922300349",
    "label": "Singer-songwriter Revival (Phase I: Rock)",
    "years": "2016 — 2019",
    "color": "#ff6251",
    "bg": "rgba(255,98,81,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776922398542",
    "label": "Singer-songwriter revival (Phase II: Folk)",
    "years": "2020 — 2023",
    "color": "#b18cfe",
    "bg": "rgba(177,140,254,0.1)",
    "desc": ""
  },
  {
    "id": "era_1776922442721",
    "label": "Alt-Country Revival",
    "years": "2023 — 2026",
    "color": "#006d8f",
    "bg": "rgba(0,109,143,0.1)",
    "desc": ""
  }
];
const ENTRIES = [
  {
    "type": "note",
    "era": "era_1776908543422",
    "movement": "",
    "title": "",
    "body": "Rock music entered its flop period around mid 1970s and I really struggle to put relevant rock records here. Lucky for us, so many touching, enduring pieces of great music was being made outside the Anglosphere, or in genres beyond the confines of rock that would later blend into indie."
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1964,
    "title": "Presenting the Fabulous Ronettes",
    "artist": "The Ronettes",
    "tagline": "Shoegaze",
    "art": "https://m.media-amazon.com/images/I/71sl15j3tzL.jpg",
    "audio": "https://open.spotify.com/track/1WN4uNclrDuczTO3bCr8s1",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1965,
    "title": "Here Are the Sonics",
    "artist": "The Sonics",
    "tagline": "Punk",
    "art": "https://m.media-amazon.com/images/I/816v2anpWkL.jpg",
    "audio": "https://open.spotify.com/track/2uXkW8uJcOIhlbUatEPLPs",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1966,
    "title": "Pet Sounds",
    "artist": "The Beach Boys",
    "tagline": "Everything - the harmony stacking, lush production and nostalgia as an idea",
    "art": "https://a1.mzstatic.com/r40/Music116/v4/35/bb/c4/35bbc4eb-9387-97b0-b138-64b7a949ea43/13UABIM03512.rgb.jpg",
    "audio": "https://open.spotify.com/track/2xNZK0n7SV7qvV1AlH30Dp",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1967,
    "title": "The Velvet Underground & Nico",
    "artist": "Velvet Underground, Nico",
    "tagline": "Everything - punk, noise rock, psychedelia, twee, the irreverent songwriting",
    "art": "https://m.media-amazon.com/images/I/61wa4WGHXnL.jpg",
    "audio": "https://open.spotify.com/track/3fElupNRLRJ0tbUDahPrAb",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1967,
    "title": "Forever Changes",
    "artist": "Love",
    "tagline": "Psychedelia",
    "art": "https://m.media-amazon.com/images/I/71-A3aHB7iL.jpg",
    "audio": "https://open.spotify.com/track/1XuccRABkfUVB4FjSVhjL1",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1968,
    "title": "Silver Apples",
    "artist": "Silver Apples",
    "tagline": "Electronic",
    "art": "https://m.media-amazon.com/images/I/81fMA9VLXSL.jpg",
    "audio": "https://open.spotify.com/track/1uXOJMO6bUhTl439u6vtSa",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1968,
    "title": "Eli and the Thirteenth Confession",
    "artist": "Laura Nyro",
    "tagline": "Art pop, world-building pop albums, chamber pop",
    "art": "https://m.media-amazon.com/images/I/617HuUYyIyL.jpg",
    "audio": "https://open.spotify.com/track/04x9RfuAP5Pyce6fYzK9Xp",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1969,
    "title": "Five Leaves Left",
    "artist": "Nick Drake",
    "tagline": "Singer-songwriter",
    "art": "https://m.media-amazon.com/images/I/71R4epCrZqL.jpg",
    "audio": "https://open.spotify.com/track/3Uh7rAb7F0XGVpEEDwfH1k",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1969,
    "title": "Everybody knows this is nowhere",
    "artist": "Neil Young & Crazy Horse",
    "tagline": "Everything!! Slacker rock, indie rock, punk etc.",
    "art": "https://a1.mzstatic.com/r40/Music125/v4/86/05/0d/86050dc2-b99f-9e0e-1af5-549d279b7638/093624924739.jpg",
    "audio": "https://open.spotify.com/track/1vVsBCkVMYdLhgiC4F54G4",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1969,
    "title": "The Stooges",
    "artist": "The Stooges",
    "tagline": "Punk",
    "art": "https://m.media-amazon.com/images/I/81wXBWTRDiL.jpg",
    "audio": "https://open.spotify.com/track/4nJCE9UyNXhuERnSX8YgSH",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1970,
    "title": "All Things Must Pass",
    "artist": "George Harrison",
    "tagline": "(Surprisingly) everything - power pop, dream pop, shoegaze",
    "art": "https://m.media-amazon.com/images/I/81dMAHQUjRL.jpg",
    "audio": "https://open.spotify.com/track/57cZFx3KlHmx0CNNYbWO8u",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1970,
    "title": "Parallelograms",
    "artist": "Linda Perhacs",
    "tagline": "Psychedelic folk, Ambient folk",
    "art": "https://m.media-amazon.com/images/I/81qIpBHV0+L.jpg",
    "audio": "https://open.spotify.com/track/7vfih9HPftqMG5BK3ghsoz",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1970,
    "title": "Sunflower",
    "artist": "The Beach Boys",
    "tagline": "Chillwave",
    "art": "https://a1.mzstatic.com/r40/Music221/v4/63/3e/30/633e302f-4683-7269-a74a-f1c1f1b896c6/13UABIM03517.rgb.jpg",
    "audio": "https://open.spotify.com/track/7y9O8sJmuX7DvmyrR7h3PY",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1971,
    "title": "Tago Mago",
    "artist": "Can",
    "tagline": "Krautrock, experimental rock",
    "art": "https://m.media-amazon.com/images/I/81KjsICb+iL.jpg",
    "audio": "https://open.spotify.com/track/7M3ErRtC3Kk5C0GqI3nN16",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1971,
    "title": "Judee Sill",
    "artist": "Judee Sill",
    "tagline": "Progressive Folk, Baroque pop",
    "art": "https://m.media-amazon.com/images/I/81CFU1I11JL.jpg",
    "audio": "https://open.spotify.com/track/3UB4aYRgyGT50AFFyDoQHb",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1971,
    "title": "Nilsson Schmilsson",
    "artist": "Harry Nilsson",
    "tagline": "Singer-songwriter",
    "art": "https://m.media-amazon.com/images/I/71fTGGjcNfL.jpg",
    "audio": "https://open.spotify.com/track/6MrILERJLA3Jcq0E9poZsp",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1972,
    "title": "#1 Record",
    "artist": "Big Star",
    "tagline": "Power pop, Alt-country, (Almost) the entire early alternative rock",
    "art": "https://m.media-amazon.com/images/I/61iF0leEIIL.jpg",
    "audio": "https://open.spotify.com/track/3BQLTtpQOYGXQY2lT3ZZeU",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1972,
    "title": "Neu!",
    "artist": "Neu!",
    "tagline": "Krautrock",
    "art": "https://m.media-amazon.com/images/I/51fkfxPWXaL.jpg",
    "audio": "https://open.spotify.com/track/1RyIA87KYGavtK0xiVXwDH",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1974,
    "title": "Winter in America",
    "artist": "Gil-Scott Heron, Brian Jackson",
    "tagline": "Jazz, hip hop & soul, care for social justice",
    "art": "https://m.media-amazon.com/images/I/81EPGloxvoL.jpg",
    "audio": "https://www.youtube.com/watch?v=m2zKdIcOV5s",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1974,
    "title": "Autobahn",
    "artist": "Kraftwerk",
    "tagline": "Electronic, Synthpop",
    "art": "https://m.media-amazon.com/images/I/61pY4hYcWAL.jpg",
    "audio": "https://open.spotify.com/track/1aIWNzwaINr2gyTEZ1ffSR",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1975,
    "title": "Horses",
    "artist": "Patti Smith",
    "tagline": "Punk",
    "art": "https://m.media-amazon.com/images/I/71ylwjRzirL.jpg",
    "audio": "https://open.spotify.com/track/272Z4tzaSMMcgrZ0R494S2",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1975,
    "title": "Inter-Dimensional Music",
    "artist": "Iasos",
    "tagline": "Ambient, New-Age",
    "art": "https://m.media-amazon.com/images/I/611rfALp-bL.jpg",
    "audio": "https://open.spotify.com/track/6JR1XlStv1gnRLT7sNek4q",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1975,
    "title": "Sowiesoso",
    "artist": "Cluster",
    "tagline": "Ambient, Electronic",
    "art": "https://m.media-amazon.com/images/I/61BMPjJpjzL.jpg",
    "audio": "https://open.spotify.com/track/6OI7uCuLdKk8QNzjVr26XA",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1975,
    "title": "Neighborhoods",
    "artist": "Ernest Hood",
    "tagline": "Ambient, Electronic",
    "art": "https://m.media-amazon.com/images/I/91DLqX-sQEL.jpg",
    "audio": "https://open.spotify.com/track/5koo0FI4AJbBXJqKPOAGra",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1976,
    "title": "The Modern Lovers",
    "artist": "The Modern Lovers",
    "tagline": "Punk",
    "art": "https://m.media-amazon.com/images/I/71mMv4NtNSL.jpg",
    "audio": "https://open.spotify.com/track/0qRSrdDK4xj1doRViNPYwM",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776908543422",
    "year": 1976,
    "title": "Reich: Music for 18 Musicians",
    "artist": "Steve Reich",
    "tagline": "Ambient, Neo-classical",
    "art": "https://m.media-amazon.com/images/I/81VNgx+NusL.jpg",
    "audio": "https://open.spotify.com/track/6DfT97NBB9xy0J40eJEU1j",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776920202864",
    "year": 1979,
    "title": "Colossal Youth",
    "artist": "Young Marble Giants",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/51ogLqc+JjL.jpg",
    "audio": "https://open.spotify.com/track/4rzePZT91RwdJMfCsP7uD1",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "note",
    "era": "era_1776921668462",
    "movement": "",
    "title": "",
    "body": "This is the first era where I feel like it's impossible to not separate things by their region. Basically, things are moving so differently across both sides of the pond. \n\nOn the US side, well...it's giving whole house mad. Hardcore rose above (or...under?) the ashes of punk as the true dominating genre for the first few years of 80s. They are usually fast, aggressive and unpolished with deep roots in their local scenes, with their manifestos being anti-commercial, anti-establishment and anti-hipsters. As for the hipsters in New York, the no wave movement formed against the polished music of New wave, using abstract ideas to revolt any intentions of writing a good melody line. For a few years, \"making good music\" seemed to not be the focus of the US indie.\n\nEventually, people began to learn how to blend melodies into the chaos and crazy rhythms of hardcore punk, with the Replacements and Husker Du becoming the leading sounds of this era; On the other side, bands like the Descendants and Violent Femmes sang so freely about the awkwardness and angst of being an adolescent, that it became blueprints for later genres like emocore.\n\nThings are far more accessible in the UK, the pop sensibility is still there, mostly because their power-pop influenced, guitar based \"indie\" sound is developed as a response to the highly produced, synth-heavy New-wave and later New Romantics movements. "
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1979,
    "title": "\"Boys Don't Cry\"",
    "artist": "The Cure",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61t3zlPjWGL.jpg",
    "audio": "https://open.spotify.com/track/4dneV7C1yDt9UtyxrQY375",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Jangle pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1980,
    "title": "Return of the Durutti Column",
    "artist": "The Durutti Column",
    "tagline": "",
    "art": "https://i.discogs.com/hZVxwRFC8m52nJfEc30Z_SDzqlxEm-TQxRsAICWSlGM/rs:fit/g:sm/q:90/h:600/w:563/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM4NjQ0/NjgtMTM0NzQ3MTk4/Ni0zMjA0LmpwZWc.jpeg",
    "audio": "https://open.spotify.com/track/2oeLt7N1amHZiev27FvKE2",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Factory Records",
      "Dream pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1980,
    "title": "Crazy Rhythms",
    "artist": "The Feelies",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71J8ygjho7L.jpg",
    "audio": "https://open.spotify.com/track/792kje520t5JZlA81M8tPd",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Jangle pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1980,
    "title": "Seventeen Seconds",
    "artist": "The Cure",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/51oaxeJJKcL.jpg",
    "audio": "https://open.spotify.com/track/3O4TPMOgChXOerSdB5WENH",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Goth rock"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1980,
    "title": "Strange Boutique",
    "artist": "The Monochrome Set",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71igwEEOhUL.jpg",
    "audio": "https://open.spotify.com/track/67UNx9ozIC8Hpo9Mc3k7QJ",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1981,
    "title": "Youth in America",
    "artist": "Wipers",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81wl23FS1FL.jpg",
    "audio": "https://open.spotify.com/track/59RkLuqY3LSqK3rJGds6cP",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Hardcore"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1981,
    "title": "Signals, Calls, and Marches",
    "artist": "Mission of Burma",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A144637uf-L.jpg",
    "audio": "https://open.spotify.com/track/3bSKHihztyH9D1ZyQsoqzI",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Hardcore"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1982,
    "title": "The Cleaners from Venus",
    "artist": "Midnight Cleaners",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91Q5Bu+xwVL.jpg",
    "audio": "https://open.spotify.com/track/5hokd9FpZOTtsOK9XW8sFD",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Jangle pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1982,
    "title": "Milo goes to college",
    "artist": "The Descendents",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91vWFeutS2L.jpg",
    "audio": "https://open.spotify.com/track/1XFG00rEeHaDIPOQv9LTYs",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Hardcore"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1982,
    "title": "After the Snow",
    "artist": "Modern English",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91yOXfxmPVL.jpg",
    "audio": "https://open.spotify.com/track/6J2rMSRhgb4HuX6dWgM3nJ",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Jangle pop",
      "4AD"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1982,
    "title": "The Days of Wine and Roses",
    "artist": "The Dream Syndicate",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61IkBg1JzZL.jpg",
    "audio": "https://open.spotify.com/track/6dgprZCV6TmIJaawCdXayu",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Paisley Underground",
      "Rough Trade"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1983,
    "title": "Murmur",
    "artist": "R.E.M.",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91DKk4dFukL.jpg",
    "audio": "https://open.spotify.com/track/46dGFTD918NMz1IP1rPJXO",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Jangle pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1983,
    "title": "Dreams Less Sweet",
    "artist": "Psychic TV",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71XIW7vbWAL.jpg",
    "audio": "https://open.spotify.com/track/1sscw7V4XQeLElIUvMSG2q",
    "tier": "",
    "movement": "off-trend",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Industrial"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1983,
    "title": "Head Over Heels",
    "artist": "Cocteau Twins",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A1vEG5M259L.jpg",
    "audio": "https://open.spotify.com/track/28gz2W2KMsn1QnvojoWPqv",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Goth rock"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1983,
    "title": "Soul Mining",
    "artist": "The The",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/7112OxcNJqL.jpg",
    "audio": "https://open.spotify.com/track/3zf2eLN9Yf8ayZO5cn4Xh5",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Synthpop",
      "4AD"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1983,
    "title": "Violent Femmes",
    "artist": "Violent Femmes",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81PE3Ar81PL.jpg",
    "audio": "https://open.spotify.com/track/7jIAttgQTpLDoNtykIQXjH",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Folk punk"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Let It Be",
    "artist": "The Replacement",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81nJBUVwezL.jpg",
    "audio": "https://open.spotify.com/track/77EwrXeCpbMMlWHqhdeFxJ",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Ocean Rain",
    "artist": "Echo & the Bunnymen",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music115/v4/2d/99/89/2d998936-e611-01a4-1a49-f29d8215666a/mzi.ocbcfibz.jpg",
    "audio": "https://open.spotify.com/track/0cOf4csnt4DeXSkFmBjULw",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Goth rock"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Hatful of Hollow",
    "artist": "The Smiths",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music115/v4/f4/00/d1/f400d1dd-5dd6-48d3-43fc-c581dec149fc/825646642854.jpg",
    "audio": "https://open.spotify.com/track/1xaTREM89RbIxkcjlpf4Uw",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Zen Arcade",
    "artist": "Husker Dü",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91gyTBKygaL.jpg",
    "audio": "https://open.spotify.com/track/523qoxtSZJE2io945dAkVk",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "From Her to Eternity",
    "artist": "Nick Cave & The Bad Seeds",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71t-kEI9TgL.jpg",
    "audio": "https://open.spotify.com/track/1gSveqp4kkxyotKeSEGWZr",
    "tier": "",
    "movement": "off-trend",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Goth rock"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Double Nickels on the Dime",
    "artist": "Minutemen",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91FhkXo6LSL.jpg",
    "audio": "https://open.spotify.com/track/21vp1orbqySVyww9ngW44w",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Post-hardcore"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1984,
    "title": "Treasure",
    "artist": "Cocteau Twins",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91ey0XSvapL.jpg",
    "audio": "https://open.spotify.com/track/1ZnXuijpwEBjhNxpEnb8WH",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Goth rock",
      "Dream pop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Maiden's Milk",
    "artist": "Meat Puppets",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71wQSy-jtFL.jpg",
    "audio": "https://open.spotify.com/track/2F5yivraxiFoclBLWmgJRN",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Country punk"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Tim",
    "artist": "The Replacements",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91-xozS1q8L.jpg",
    "audio": "https://open.spotify.com/track/14g6foD6sxO1qgkDKuPgWv",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Psychocandy",
    "artist": "Jesus and Mary Chain",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91xJPzgu-ZL.jpg",
    "audio": "https://open.spotify.com/track/1CapNlKgeOWlBEE54CRamd",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Shoegaze"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Rites of Spring",
    "artist": "Rites of Spring",
    "tagline": "",
    "art": "https://i.discogs.com/kPxVsGyboOnIwLYaH0sOFk6aAhYu_Rh6h39HhQZI2lg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwNjMw/MzAtMTI2MTc3NjAy/Ni5qcGVn.jpeg",
    "audio": "https://open.spotify.com/track/6AEY7T6O4bunqcEoqzBVJ2",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "Hardcore",
      "Emo"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Steve McQueen",
    "artist": "Prefab Sprout",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81Mv-zpyy0L.jpg",
    "audio": "https://open.spotify.com/track/7bRcgBFPDgWhVuopP5x6MW",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [
      "Sophistipop"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1985,
    "title": "Bad Moon Rising",
    "artist": "Sonic Youth",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81x8iyF2HJL.jpg",
    "audio": "https://open.spotify.com/track/6r8LzSDPjgffByaanHgERH",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [
      "No Wave"
    ],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1986,
    "title": "The Queen Is Dead",
    "artist": "The Smiths",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71902D0u9ZL.jpg",
    "audio": "https://open.spotify.com/track/0WQiDwKJclirSYG9v5tayI",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776921668462",
    "year": 1986,
    "title": "Evol",
    "artist": "Sonic Youth",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81c66Y578eL.jpg",
    "audio": "https://open.spotify.com/track/0mYaDPgvNkXgXS3TVjuITD",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776471732213",
    "year": 2001,
    "title": "Is This It",
    "artist": "The Strokes",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Features115/v4/ea/04/d4/ea04d45d-6f5d-ede6-fb64-71f3e6a6e62f/dj.ojkzzidd.jpg",
    "audio": "https://open.spotify.com/track/3SUusuA9jH1v6PVwtYMbdv",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "note",
    "era": "era_1776446456442",
    "movement": "",
    "title": "The sound of indie softens",
    "body": ""
  },
  {
    "type": "note",
    "era": "era_1776446456442",
    "movement": "alt-country-part-ii-2000s",
    "title": "",
    "body": "Aesthetic-wise, alt-country maintained its style in this decade, blending folk, rock and country elements and pretty much carried on the greatness in the 1990s . Artists like Gillian Welch, Bill Callahan, Wilco and Silver Jews built upon their styles and went on to release great records. Other artists like Jason Molina and Drive-by-truckers emerged out of the scene and made some of the defining records of this decade. Some artists would become a mainstay in this genre, but the craze gradually died down during the latter part of the decade due to more electronic and pop-focused indie rock acts taking over the spotlight and the derogative term \"dad-rock\" being coined to describe this genre. Moreover, quite a few key artists slowed down with the outputs or unfortunately passed away. Nevertheless, many records in this decade would proven to be influential in the alt-country revival two decades later. "
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 1970,
    "title": "Just Another Diamond Day",
    "artist": "Vashti Bunyan",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81uvFbhEoGL.jpg",
    "audio": "https://open.spotify.com/track/6bqB7idfAnJVisSMQA1mZQ",
    "tier": "influence",
    "movement": "freak-folk",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 1970,
    "title": "Parallelograms",
    "artist": "Linda Perhacs",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81qIpBHV0+L.jpg",
    "audio": "https://open.spotify.com/track/7vfih9HPftqMG5BK3ghsoz",
    "tier": "influence",
    "movement": "freak-folk",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 1998,
    "title": "In the Aeroplane over the Sea ",
    "artist": "Neutral Milk Hotel",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81VeNvD9s1L.jpg",
    "audio": "https://open.spotify.com/track/1NiAMp0CzUdG6e97VYRB1a",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2000,
    "title": "The Moon and Antarctica",
    "artist": "Modest Mouse",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/714p+DCMvnL.jpg",
    "audio": "https://open.spotify.com/track/1pPqVrG2RCHXx81Aw4xp99",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2001,
    "title": "Oh, Inverted World",
    "artist": "The Shins",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/813UKnSxoYL.jpg",
    "audio": "https://open.spotify.com/track/4Omfr1OV4e0eaLcPe5JFRa",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2001,
    "title": "The Glow, Pt. 2",
    "artist": "The Microphones",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81gokR-24HL.jpg",
    "audio": "https://open.spotify.com/track/1bAZV1EBTRi9t1cVg75i8t",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2001,
    "title": "You Forgot It In People",
    "artist": "Broken Social Scene",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music114/v4/c6/b1/49/c6b14990-0dc7-3763-0e4d-acf243f1b8ee/00827590010062.rgb.jpg",
    "audio": "https://open.spotify.com/track/3Cl35xMXJUEhpPaYBeNUQR",
    "tier": "essential",
    "movement": "canadian-confessional-big-band-rock",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2001,
    "title": "Time (Revelator)",
    "artist": "Gillian Welch",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81kubrhNGfL.jpg",
    "audio": "https://open.spotify.com/track/0kGN0PYexsQZfjrII4fyVU",
    "tier": "essential",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2001,
    "title": "Takeoffs and Landings",
    "artist": "Rilo Kiley",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61UPWu1-dpL.jpg",
    "audio": "https://open.spotify.com/track/1YDMec7wxyKoD0AtOfGG9Q",
    "tier": "",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2002,
    "title": "Yankee Hotel Foxtrot",
    "artist": "Wilco",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81EyhH+mpPL.jpg",
    "audio": "https://open.spotify.com/track/4wd09wCccmxUB7XVJp0RNn",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2002,
    "title": "Blacklisted",
    "artist": "Neko Case",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81nHknuLHGL.jpg",
    "audio": "https://open.spotify.com/track/61YAuOQzU7ZFoBSpqaMyiI",
    "tier": "",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2003,
    "title": "Magnolia Electric Co.",
    "artist": "Songs: Ohia",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81951LMYANL.jpg",
    "audio": "https://open.spotify.com/track/5Plx6OhvSukqCRdZ52wUXz",
    "tier": "essential",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2003,
    "title": "Greetings from Michigan, the Great Lake State",
    "artist": "Sufjan Stevens",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81zCz-EQ5wL.jpg",
    "audio": "https://open.spotify.com/track/43ZSSBSW2Y3QcStk1fv2fl",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2003,
    "title": "Transatlanticism",
    "artist": "Death Cab for Cutie",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71GPvbdtQJL.jpg",
    "audio": "https://open.spotify.com/track/4LF1dMlOHe8VfmMut7YiIs",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2003,
    "title": "Transfiguration of Vincent",
    "artist": "M. Ward",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music211/v4/5e/3e/3a/5e3e3a2d-2405-efd7-57b7-97dbe79a1a5f/57128.jpg",
    "audio": "https://open.spotify.com/track/7EJroHJlfFQOnEpuHousQV",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Let It Die",
    "artist": "Feist",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music114/v4/af/3e/e5/af3ee517-1998-5e18-8805-36d4e894a687/00602498292129.rgb.jpg",
    "audio": "https://open.spotify.com/track/6rouj6pwJgrh6whnljzXPd",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Our Endless Numbered Days",
    "artist": "Iron & Wine",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91tgZjyR9nL.jpg",
    "audio": "https://open.spotify.com/track/2heKDrjNvoeLfzLorO4g5R",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Seven Swans",
    "artist": "Sufjan Stevens",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71Q6KTi6H9L.jpg",
    "audio": "https://open.spotify.com/track/5lzLedCPBk2A36KQUWEt5P",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Funeral",
    "artist": "Arcade Fire",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81JWy8tc-4L.jpg",
    "audio": "https://open.spotify.com/track/0xOeB16JDbBJBJKSdHbElT",
    "tier": "essential",
    "movement": "canadian-confessional-big-band-rock",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "The Milk-Eyed Mender",
    "artist": "Joanna Newsom",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81YBcQrnXRL.jpg",
    "audio": "https://www.youtube.com/watch?v=47yuiPK01kg",
    "tier": "",
    "movement": "freak-folk",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Set Yourself on Fire",
    "artist": "Stars",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81LlJPWbFJL.jpg",
    "audio": "https://open.spotify.com/track/6XGKlssGb3oE9IUCvjLthd",
    "tier": "",
    "movement": "canadian-confessional-big-band-rock",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "Sung Tongs",
    "artist": "Animal Collective",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71GXNNqJRQL.jpg",
    "audio": "https://open.spotify.com/track/0RcJoi4OLdWWvhwQAZ25Oa",
    "tier": "",
    "movement": "freak-folk",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2004,
    "title": "A Ghost is Born",
    "artist": "Wilco",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61PLjC8YZ2L.jpg",
    "audio": "https://open.spotify.com/track/2CJpJK9awyjKS98KOPfivw",
    "tier": "",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2005,
    "title": "Picaresque",
    "artist": "The Decemberist",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71Kspwy9LEL.jpg",
    "audio": "https://open.spotify.com/track/569cwY6Yu2W75l3K3XFndC",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2005,
    "title": "Illinois",
    "artist": "Sufjan Stevens",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81qDBivALmL.jpg",
    "audio": "https://open.spotify.com/track/1yupbrI7ROhigIHpQBevPh",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2005,
    "title": "I Am a Bird Now",
    "artist": "Anohni and the Johnsons",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91rapDR6NCL.jpg",
    "audio": "https://open.spotify.com/track/37YJOz90ri4sjyo4uyCLXA",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2005,
    "title": "Apologies to the Queen Mary",
    "artist": "Wolf Parade",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71nCMnWfYEL.jpg",
    "audio": "https://open.spotify.com/track/7zxikeAavSLQVGocbK2nau",
    "tier": "",
    "movement": "canadian-confessional-big-band-rock",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2006,
    "title": "The Greatest",
    "artist": "Cat Power",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61VKEqWvvNL.jpg",
    "audio": "https://open.spotify.com/track/0OVXLPJPDCFn1IV6bFxY1N",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2006,
    "title": "Everything All the Time",
    "artist": "Band of Horses",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music221/v4/de/90/fb/de90fb54-a087-6025-fb13-3334537688c2/098787173062.png",
    "audio": "https://open.spotify.com/track/4kxlUznSzzc8li5kPtdAug",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2007,
    "title": "The Reminder",
    "artist": "Feist",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61ylSREsysL.jpg",
    "audio": "https://open.spotify.com/track/2CzWeyC9zlDpIOZPUUKrBW",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2007,
    "title": "Marry Me",
    "artist": "St. Vincent",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61aIkSGUnjL.jpg",
    "audio": "https://open.spotify.com/track/3wOaJ2wFbkGOOzhvGAgwLX",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2007,
    "title": "Boxer",
    "artist": "The National",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81Uih3A8yUL.jpg",
    "audio": "https://open.spotify.com/track/5SA1pmhLHV02cWxPm1t6q3",
    "tier": "postinfluence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2007,
    "title": "Sky Blue Sky",
    "artist": "Wilco",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81zJM7BFCxL.jpg",
    "audio": "https://open.spotify.com/track/6L0BBPYeWnaQJeDa0ox0IA",
    "tier": "",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776446456442",
    "year": 2009,
    "title": "Sometimes I Wish We Were An Eagle",
    "artist": "Bill Callahan",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61TzrEGAOoL.jpg",
    "audio": "https://open.spotify.com/track/3KZRkM7Uv0F2oCTUHAvv0a",
    "tier": "essential",
    "movement": "alt-country-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "note",
    "era": "sleaze",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "title": "",
    "body": "The sound of chamber pop didn't change much throughout the 2000s.\n\nMusic styles are transient, good melodies endure. Indie pop is a style that can be easily co-opted by countless copycats, but at the end of the day what we want is just a really catchy song. I realized I just kept adding entries from the same bands, but I'll be damned if they weren't great"
  },
  {
    "type": "note",
    "era": "sleaze",
    "movement": "shoegaze-part-ii-2000s",
    "title": "",
    "body": "Shoegaze entered a fallow period for the better part of the 2000s. Just like Britpop completely dominated Shoegaze in the 90s UK, the revival of garage- and punk rock, and later indie rock took up the whole space. The big Shoegaze acts in the 1990s went into hiatus, while the existing new ones remained on the fringes. Nevertheless, this decade saw Shoegaze blending into other genres like post-punk (Autolux, Blonde Redhead), indie pop (The Radio Dept.), electronica (Sweet Trip) and ambient (M83). Things picked up again at the end of the decade, with a new generation of acts (Deerhunter, A Sunny Day in Glasgow) bringing in a new sound, exploring the elements of Shoegaze to evoke nostalgia feelings."
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 1966,
    "title": "Pet Sounds",
    "artist": "The Beach Boys",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music116/v4/35/bb/c4/35bbc4eb-9387-97b0-b138-64b7a949ea43/13UABIM03512.rgb.jpg",
    "audio": "https://open.spotify.com/track/2xNZK0n7SV7qvV1AlH30Dp",
    "tier": "influence",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 1977,
    "title": "Pink Flag",
    "artist": "Wire",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71-0UTurYcL.jpg",
    "audio": "https://open.spotify.com/track/0bN5W8EhIJhh6zvgeNG57J",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 1983,
    "title": "Come Away with ESG",
    "artist": "ESG",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/614wXCdNKDL.jpg",
    "audio": "https://open.spotify.com/track/0iD94fatV4gLMmOQhNTQx6",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 1999,
    "title": "Emergency & I",
    "artist": "The Dismemberment Plan",
    "tagline": "Slacker rock with a dance beat",
    "art": "https://m.media-amazon.com/images/I/8126menEM-L.jpg",
    "audio": "https://open.spotify.com/track/2mWJVuJsQIFg0fnRYcD8zz",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2000,
    "title": "Suburban Light",
    "artist": "The Clientele",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music221/v4/20/7a/61/207a616b-9778-9fb0-ba97-5d0d883a2d54/56947.jpg",
    "audio": "https://open.spotify.com/track/2SjjbvFl45Wo8ZM5dlRdZZ",
    "tier": "essential",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2000,
    "title": "And Then Nothing Turned Itself Inside-Out",
    "artist": "Yo La Tengo",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music116/v4/73/58/28/735828d8-1b08-2672-519a-a61839adbbf2/744861037132.png",
    "audio": "https://open.spotify.com/track/5s91S8hSrJXqYdhwHOEioV",
    "tier": "",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2001,
    "title": "They Threw Us All in a Trench and Stuck a Monument on Top",
    "artist": "Liars",
    "tagline": "Wait, this is not an LCD Soundsystem track?",
    "art": "https://m.media-amazon.com/images/I/51Nhp1QLNsL.jpg",
    "audio": "https://open.spotify.com/track/3FBfFxUtt6WaLH8wo9Q9va",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2002,
    "title": "..Lo Que Va a Encandilar Es El Día",
    "artist": "Jaime Sin Tierra",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/B1F--8gryJS.jpg",
    "audio": "https://open.spotify.com/track/2GDdWDZUQHCsGa0LsbEUT7",
    "tier": "",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Echoes",
    "artist": "The Rapture",
    "tagline": "Start of the James Murphy reign",
    "art": "https://m.media-amazon.com/images/I/61wnEvvwWzL.jpg",
    "audio": "https://open.spotify.com/track/1bKffBd9glU944RMrWjjky",
    "tier": "pioneer",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Deep Cuts",
    "rating": 4,
    "artist": "The Knife",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61N1YtYBDxL.jpg",
    "audio": "https://open.spotify.com/track/5P2hEcHjoNMh33EsFPPOJE",
    "tier": "pioneer",
    "artBg": "#181818",
    "artColor": "#999",
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "movement": ""
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Give Up",
    "rating": 4,
    "artist": "The Postal Service",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71b7LWlXCcL.jpg",
    "audio": "https://open.spotify.com/track/2Lum7cLDAZGbDVLXHyisEa",
    "tier": "pioneer",
    "artBg": "#181818",
    "artColor": "#999",
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "movement": "indietronica"
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Lesser Matters",
    "artist": "The Radio Dept.",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A177i3s1zCL.jpg",
    "audio": "https://open.spotify.com/track/2w1fWah18grJInzEuhiJZU",
    "tier": "essential",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Summer Sun",
    "artist": "Yo La Tengo",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71d74akrYOL.jpg",
    "audio": "https://open.spotify.com/track/5nunaC0CNOswAsk98i0Ugq",
    "tier": "",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Dead Cities, Red Seas & Lost Ghosts",
    "artist": "M83",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71BWrJndmyL.jpg",
    "audio": "https://open.spotify.com/track/5Y8sPOwWupGEGM7ifBDR7F",
    "tier": "essential",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Velocity : Comfort : Design",
    "artist": "Sweet Trip",
    "tagline": "",
    "art": "https://i.discogs.com/g_aJbkLwoIyU69is2RwRKGsrDKvLiuGhiiX_83ksWl0/rs:fit/g:sm/q:90/h:585/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5NzY5/NzI4LTE2MjgyODY5/NDMtMTk3My5wbmc.jpeg",
    "audio": "https://open.spotify.com/track/50bVt9oMOYwnFe2uf4OSpf",
    "tier": "essential",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2003,
    "title": "Lesser Matters",
    "artist": "The Radio Dept.",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A177i3s1zCL.jpg",
    "audio": "https://open.spotify.com/track/6NyvZ5pfq4eShEZXWARosP",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2004,
    "title": "Smile",
    "artist": "Brian Wilson",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music/y2004/m11/d09/h00/s06.ceiowlmw.jpg",
    "audio": "https://open.spotify.com/track/6GYFPOqatb9gRhbrhwkcJB",
    "tier": "influence",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2004,
    "title": "Sung Tongs",
    "artist": "Animal Collective",
    "tagline": "",
    "art": "https://i.discogs.com/uLUIK4E4rfUsaotZzx_Os5iROImMntkXTX1K_Fa6Hxc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTc4OTc0/NTAtMTQ1MTIxMTM4/MS03MDg4LmpwZWc.jpeg",
    "audio": "https://open.spotify.com/track/1aeb7ZqvgefBWgjhfoCF1A",
    "tier": "pioneer",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2004,
    "title": "Future Perfect",
    "artist": "Autolux",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61l-QIUZB5L.jpg",
    "audio": "https://open.spotify.com/track/3RR8JZGjOZ1bYPewpJkG8I",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2004,
    "title": "Winks and Kisses",
    "artist": "Airiel",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A1VZ6sHxjFL.jpg",
    "audio": "https://open.spotify.com/track/03vkICPhl5N7CFmasxCERG",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2005,
    "title": "LCD Soundsystem",
    "artist": "LCD Soundsystem",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81wkTb4nuLL.jpg",
    "audio": "https://open.spotify.com/track/73mlvsfJM2qwlDUJxeaatI",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2006,
    "title": "So This Is Goodbye",
    "artist": "Junior Boys",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music124/v4/cb/ca/34/cbca3478-7191-9b69-0a93-bd159da27e60/mzi.aosquyzu.jpg",
    "audio": "https://open.spotify.com/track/5nqG4Q8RDIkE4dxxweGYYg",
    "tier": "essential",
    "movement": "indietronica",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2006,
    "title": "The Warning",
    "artist": "Hot Chip",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71oMtsy-KsL.jpg",
    "audio": "https://open.spotify.com/track/0PCYXSyESysJ1Eodxjyn9p",
    "tier": "",
    "movement": "indietronica",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2006,
    "title": "Yellow House",
    "artist": "Grizzly Bear",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61qw0DGGaVL.jpg",
    "audio": "https://open.spotify.com/track/3MzmMlvgGRndF0nBc4krrb",
    "tier": "essential",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2006,
    "title": "Whatever People Say I Am, That's What I'm Not",
    "artist": "Arctic Monkeys",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61-MakR51dL.jpg",
    "audio": "https://open.spotify.com/track/2fyIS6GXMgUcSv4oejx63f",
    "tier": "",
    "movement": "indie-pop-bands",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 3,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2006,
    "title": "Fleeting Joys",
    "artist": "Despondent Transponder",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81ko9gFMygL.jpg",
    "audio": "https://open.spotify.com/track/6iSmq9NIju7uj3MwE8YCmu",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "Justice",
    "artist": "Justice",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61tDl1Q09dL.jpg",
    "audio": "https://open.spotify.com/track/33yAEqzKXexYM3WlOYtTfQ",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "Sound of Silver",
    "artist": "LCD Soundsystem",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71JOQISYxGL.jpg",
    "audio": "https://open.spotify.com/track/2Ud3deeqLAG988pfW0Kwcl",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "Person Pitch",
    "artist": "Panda Bear",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71fWvQFlImL.jpg",
    "audio": "https://open.spotify.com/track/4DjLXaUaqbm70uguXzDJmm",
    "tier": "essential",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "God Save the Clientele",
    "artist": "The Clientele",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/919ZOsgxUnL.jpg",
    "audio": "https://open.spotify.com/track/7gHY5qrkNc7uuUHoyG87sS",
    "tier": "",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "Kala",
    "artist": "M.I.A.",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91rOMFqtj6L.jpg",
    "audio": "https://open.spotify.com/track/1ixbwbeBi5ufN4noUKmW5a",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2007,
    "title": "23",
    "artist": "Blonde Redhead",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/61jl4NqN7AL.jpg",
    "audio": "https://open.spotify.com/track/2RaGRh57p4OtzpXtr65Nws",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Oracular Spectacular",
    "artist": "MGMT",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71wM3XhEkBL.jpg",
    "audio": "https://open.spotify.com/track/1jJci4qxiYcOHhQR247rEU",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "In Ghost Colours",
    "artist": "Cut Copy",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/6184YQTkRhL.jpg",
    "audio": "https://open.spotify.com/track/00llsKdeeHRs8qPgdYl4OJ",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Hercules & Love Affair",
    "artist": "Hercules & Love Affair",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/818AF-NsHkL.jpg",
    "audio": "https://open.spotify.com/track/6vZAclrvKqH8ZZV69TISvF",
    "tier": "",
    "movement": "indietronica",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Fleet Foxes",
    "artist": "Fleet Foxes",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/91A-hzP-StL.jpg",
    "audio": "https://open.spotify.com/track/0GegHVxeozw3rdjte45Bfx",
    "tier": "",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Vampire Weekend",
    "artist": "Vampire Weekend",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81B2+GoNzbL.jpg",
    "audio": "https://open.spotify.com/track/0ful4PHfTIxzXiZSZsXQ0H",
    "tier": "",
    "movement": "indie-pop-bands",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Vivian Girls",
    "artist": "Vivian Girls",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music112/v4/83/1a/41/831a413e-2c4d-d4d3-770f-d260a3f9f410/644110039194.png",
    "audio": "https://open.spotify.com/track/3VPJN3AbTWDa4sG6SLSI4D",
    "tier": "",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Santigold",
    "artist": "Santigold",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81g7SwQU9WL.jpg",
    "audio": "https://open.spotify.com/track/7I8IDnrsXCMnC7sUu5njJ3",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Women",
    "artist": "Women",
    "tagline": "",
    "art": "https://i.discogs.com/ad9DXKrC8pP7eEgMYSJVJdOrNzALXfD0_SfuvInVD5k/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2MzE5/NTUtMTMzODEzOTY1/OS04NzI2LmpwZWc.jpeg",
    "audio": "https://open.spotify.com/track/1XgfMaZadpNbVIwZljGurA",
    "tier": "essential",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Some Are Lakes",
    "artist": "Land of Talk",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81vRuQ7UjnL.jpg",
    "audio": "https://open.spotify.com/track/7iFSpCM9pY6fnkWkXw59fU",
    "tier": "",
    "movement": "off-trend-other-pioneering-sounds-in-the-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Nouns",
    "artist": "No Age",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71J+sSSp5vL.jpg",
    "audio": "https://open.spotify.com/track/2FjronTpJVHFTDH5gaC64w",
    "tier": "",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2008,
    "title": "Microcastle",
    "artist": "Deerhunter",
    "tagline": "",
    "art": "https://i.discogs.com/HRj0rtPFYMMAlULG_XkaHO2rtjyrWEApwS3JqOJiBCA/rs:fit/g:sm/q:90/h:500/w:500/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTYxOTY2/MTUtMTQxMzQ2OTA3/Mi0yOTE4LmpwZWc.jpeg",
    "audio": "https://open.spotify.com/track/60jhynlMWvL9jqMh11BPFT",
    "tier": "essential",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "It's Blitz!",
    "artist": "The Yeah Yeah Yeahs",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/710zn71u-iL.jpg",
    "audio": "https://open.spotify.com/track/4WiIscpBgQFm5qIyjoH7M4",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Wolfgang Amadeus Phoenix",
    "artist": "Phoenix",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music211/v4/28/8d/ab/288dabdd-f8de-80f6-1aab-40a24cb1b33f/00892038002190_Cover.jpg",
    "audio": "https://open.spotify.com/track/68hYdj3GepWm2R202KhJT7",
    "tier": "",
    "movement": "indie-pop-bands",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 3,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Merriweather Post Pavilion",
    "artist": "Animal Collective",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/811CpATN+8L.jpg",
    "audio": "https://open.spotify.com/track/26JkaeeVVIPLquHEsf7YJd",
    "tier": "essential",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Veckatimest",
    "artist": "Grizzly Bear",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/81ZAhWmkz-L.jpg",
    "audio": "https://open.spotify.com/track/04uR2cdkgiaLIzebPcs25m",
    "tier": "",
    "movement": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Wavvves",
    "artist": "Wavves",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71TMZHKDkLL.jpg",
    "audio": "https://open.spotify.com/track/6acTYR4Xy4QhICzBc7rzY1",
    "tier": "",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "\"Sun was high (and so was I)\"",
    "artist": "Best Coast",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music/3d/e1/39/mzi.ieeayfab.jpg",
    "audio": "https://www.youtube.com/watch?v=eLMC4FCvN_8",
    "tier": "",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "My Maudlin Career",
    "artist": "Camera Obscura",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/A1yFa-eVEUL.jpg",
    "audio": "https://open.spotify.com/track/7Mb0qE443GpOcgkmgS4lP1",
    "tier": "essential",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "You Will Never Know Why",
    "artist": "Sweet Trip",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music125/v4/a3/2b/b2/a32bb267-1d73-34b6-a6c2-a34c85a5c241/708527022221.jpg",
    "audio": "https://open.spotify.com/track/62ocXa3rr5qUWI3GAhWnaH",
    "tier": "",
    "movement": "chamber-pop-twee-pop-and-indie-pop",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Introverted Romance in Our Troubled Minds",
    "artist": "P.S.Eliot",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music115/v4/7a/53/e4/7a53e4e5-ef73-3b6a-f624-de29187c15d6/634457472266.jpg",
    "audio": "https://open.spotify.com/track/59cMht6Ac7doFBTDZ22xmC",
    "tier": "",
    "movement": "off-trend-other-pioneering-sounds-in-the-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Born Again Revisited",
    "artist": "Times New Viking",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/913UTwJzKML.jpg",
    "audio": "https://open.spotify.com/track/79Nc4niVTrRN5GQuTmjVFe",
    "tier": "",
    "movement": "noise-pop-and-shitgaze-music",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "sleaze",
    "year": 2009,
    "title": "Ashes Grammar",
    "artist": "A Sunny Day in Glasgow",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/912+hxhsTHL.jpg",
    "audio": "https://open.spotify.com/track/1zCKs29Y9ZXAONsd7smLK4",
    "tier": "",
    "movement": "shoegaze-part-ii-2000s",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "note",
    "era": "era_1776312948356",
    "movement": "",
    "title": "",
    "body": ""
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 1966,
    "title": "Pet Sounds",
    "artist": "The Beach Boys",
    "tagline": "what is in the music that makes us feel nostalgic? is it ...",
    "art": "https://a1.mzstatic.com/r40/Music116/v4/35/bb/c4/35bbc4eb-9387-97b0-b138-64b7a949ea43/13UABIM03512.rgb.jpg",
    "audio": "https://open.spotify.com/track/2Gy7qnDwt8Z3MNxqat4CsK",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 1992,
    "title": "Drop Nineteens",
    "artist": "Delaware",
    "tagline": "...the thrashing sounds of shoegaze distortion...",
    "art": "https://m.media-amazon.com/images/I/91rWMQ6jSRL.jpg",
    "audio": "https://open.spotify.com/track/40ABtf917Ghhi2tkQDNOdn",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 1994,
    "title": "Bee Thousand",
    "artist": "Guided by Voices",
    "tagline": "...the lo-fi texture...",
    "art": "https://m.media-amazon.com/images/I/61x45vDDbFL.jpg",
    "audio": "https://open.spotify.com/track/4SrE9bJwNC2ldX8rAXsrKE",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 1995,
    "title": "Mellon Collie and the Infinite Sadness",
    "artist": "Smashing Pumpkins ",
    "tagline": "...or just a few chords...",
    "art": "https://m.media-amazon.com/images/I/810pXBhxOkL.jpg",
    "audio": "https://open.spotify.com/track/3h5zik31hTTat9jmpCZZNC",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 1998,
    "title": "Music Has the Right to Children",
    "artist": "Boards of Canada",
    "tagline": "...through samples...",
    "art": "https://a1.mzstatic.com/r40/Features125/v4/b5/4c/c2/b54cc20d-03f5-f2c4-4a0d-9b51ad65af89/dj.txuslqgv.jpg",
    "audio": "https://open.spotify.com/track/08EgS4Nqe1jPkI9tx9Dq3S",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 2001,
    "title": "Endless Summer",
    "artist": "Fennesz",
    "tagline": "...and loops...",
    "art": "https://m.media-amazon.com/images/I/71aFesxXb3L.jpg",
    "audio": "https://open.spotify.com/track/2DYGS6lBV7lId0oviQaeJL",
    "tier": "influence",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 5,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 2009,
    "title": "\"Nobody Here\"",
    "artist": "sunsetcorps",
    "tagline": "",
    "art": "https://a1.mzstatic.com/r40/Music124/v4/8c/31/fc/8c31fcb4-63b3-fdd0-a078-8e7ea3f304b4/artwork.jpg",
    "audio": "https://www.youtube.com/watch?v=-RFunvF0mDw",
    "tier": "pioneer",
    "movement": "internet-nostalgia",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "right"
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 2009,
    "title": "Psychic Chasms",
    "artist": "Neon Indian",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/71RgMGFJmaL.jpg",
    "audio": "https://open.spotify.com/track/0oSuRJjTO7DTA1ltDuQUzM",
    "tier": "",
    "movement": "internet-nostalgia",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776312948356",
    "year": 2010,
    "title": "Causers of This",
    "artist": "Toro y Moi",
    "tagline": "",
    "art": "https://m.media-amazon.com/images/I/912Bq-aS8FL.jpg",
    "audio": "https://open.spotify.com/track/69IvMGnw15HXaVMSHxgrCb",
    "tier": "",
    "movement": "internet-nostalgia",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 4,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": [],
    "side": "left"
  },
  {
    "type": "album",
    "era": "era_1776922442721",
    "year": 2026,
    "title": "New Album",
    "artist": "Artist",
    "tagline": "",
    "art": "",
    "audio": "",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 3,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  },
  {
    "type": "album",
    "era": "era_1776922442721",
    "year": 2026,
    "title": "New Album",
    "artist": "Artist",
    "tagline": "",
    "art": "",
    "audio": "",
    "tier": "",
    "movement": "",
    "artBg": "#181818",
    "artColor": "#999",
    "rating": 3,
    "tags": [],
    "review": "",
    "context": "",
    "tracks": []
  }
];

const GENRES = {"Jangle Pop":{"desc":""},"Jangle pop":{"desc":""},"Goth rock":{"desc":""},"Goth Rock":{"desc":""},"Sophistipop":{"desc":""},"Dream pop":{"desc":""}};
const MOVEMENTS = [
  {
    "id": "the-psychedelic-pop-of-elephant-6",
    "era": "era_1776565014692",
    "label": "The Psychedelic Pop of Elephant 6",
    "desc": ""
  },
  {
    "id": "the-jazzy-sounds-of-chicago-second-wave-post-rock",
    "era": "era_1776565014692",
    "label": "The Jazzy Sounds of Chicago second-wave Post Rock",
    "desc": ""
  },
  {
    "id": "the-crescendos-in-the-third-wave-post-rock",
    "era": "era_1776565014692",
    "label": "Scandinavian Third-wave Post-rock",
    "desc": ""
  },
  {
    "id": "freak-folk",
    "era": "era_1776446456442",
    "label": "Freak Folk",
    "desc": ""
  },
  {
    "id": "canadian-confessional-big-band-rock",
    "era": "era_1776446456442",
    "label": "Canadian Confessional Big Band Rock",
    "desc": ""
  },
  {
    "id": "earnest-folk-rock",
    "era": "era_1776446456442",
    "label": "Earnest Folk Rock",
    "desc": ""
  },
  {
    "id": "alt-country-part-ii-2000s",
    "era": "era_1776446456442",
    "label": "Alt-Country (Part II: 2000s)",
    "desc": ""
  },
  {
    "id": "indietronica",
    "era": "sleaze",
    "label": "Indietronica",
    "desc": "Dance music for the after hours"
  },
  {
    "id": "indie-pop-bands",
    "era": "sleaze",
    "label": "Indie Pop Bands",
    "desc": "I don't like them ... but whatever works"
  },
  {
    "id": "pitchforkcore-gadpy-and-brian-wilson-revival",
    "era": "sleaze",
    "label": "Pitchforkcore, GADPY and Brian Wilson revival",
    "desc": "100 layers of harmonies"
  },
  {
    "id": "noise-pop-and-shitgaze-music",
    "era": "sleaze",
    "label": "Off-trend: Noise Pop and \"Shitgaze\" music",
    "desc": "I can't hear a thing..."
  },
  {
    "id": "chamber-pop-twee-pop-and-indie-pop",
    "era": "sleaze",
    "label": "Indie Pop (Part II: 2000s)",
    "desc": ""
  },
  {
    "id": "off-trend-other-pioneering-sounds-in-the-2000s",
    "era": "sleaze",
    "label": "Off-trend: Other Pioneering Sounds in the 2000s",
    "desc": "These records can be released 10 years later and would sound aged a day..."
  },
  {
    "id": "shoegaze-part-ii-2000s",
    "era": "sleaze",
    "label": "Shoegaze (Part II: 2000s)",
    "desc": ""
  },
  {
    "id": "off-trend",
    "era": "era_1776921668462",
    "label": "Off-trend",
    "desc": "",
    "dualColumn": false,
    "leftLabel": "",
    "rightLabel": ""
  },
  {
    "id": "internet-nostalgia",
    "era": "era_1776312948356",
    "label": "Internet Nostalgia",
    "desc": "",
    "dualColumn": true,
    "leftLabel": "Chillwave",
    "rightLabel": "Vaporwave"
  }
];
const SITE_CONFIG = {"kicker":"The Indie Current","titleHtml":"An incomplete guide&nbsp;<div>to the history of indie rock</div>","subtitle":""};
