const ERAS = [
  { id:'slacker',    label:'Slacker & Lo-Fi',          years:'1991–1997', color:'#b8893a', bg:'rgba(184,137,58,0.1)',  desc:'Distortion, casualness, and studied indifference to polish' },
  { id:'britpop',    label:'Post-Grunge & Britpop',     years:'1994–2001', color:'#4a7ec4', bg:'rgba(74,126,196,0.1)', desc:'Anthems, lad culture, and the British guitar revival' },
  { id:'emo',        label:'Emo & Post-Punk Revival',   years:'2001–2008', color:'#b44a7a', bg:'rgba(180,74,122,0.1)', desc:'Vulnerability, theatricality, and New York cool' },
  { id:'sleaze',     label:'Indie Sleaze',              years:'2006–2012', color:'#c4a030', bg:'rgba(196,160,48,0.1)', desc:'The last era before smartphones ate everything' },
  { id:'bedroom',    label:'Bedroom Pop & Soft Focus',  years:'2012–2019', color:'#4898c8', bg:'rgba(72,152,200,0.1)', desc:'Intimacy, lo-fi production, and SoundCloud democracy' },
  { id:'altcountry', label:'Alt-Country & New Folk',    years:'2019–Now',  color:'#c4743c', bg:'rgba(196,116,60,0.1)', desc:'Pedal steel, porch philosophy, and rural romanticism' }
];

const ENTRIES = [
  // ─── SLACKER ───
  { type:'album', era:'slacker', year:1991, title:'Nevermind', artist:'Nirvana', rating:5,
    tagline:'The album that changed alternative radio overnight',
    art:'',
    artBg:'#1a1a28', artColor:'#8888c8',
    tags:['Grunge','Seattle','Crossover'],
    review:'The album that made "alternative" a radio category. Butch Vig\'s production gave Kurt Cobain\'s self-loathing an arena scale. Cobain hated what it became — the ambivalence was the point.',
    tracks:[{n:1,t:'Smells Like Teen Spirit',h:true},{n:2,t:'In Bloom',h:false},{n:3,t:'Come as You Are',h:true},{n:4,t:'Lithium',h:true},{n:5,t:'Polly',h:false},{n:6,t:'Territorial Pissings',h:false},{n:7,t:'Drain You',h:true},{n:8,t:'Lounge Act',h:false},{n:9,t:'Stay Away',h:false},{n:10,t:'On a Plain',h:false},{n:11,t:'Something in the Way',h:true}],
    context:'Shipped 30 million copies. Replaced Michael Jackson at #1. Changed the music industry permanently.' },

  { type:'event', era:'slacker', year:1992,
    title:'Lollapalooza defines the alternative mainstream',
    eventType:'Cultural moment',
    body:'Jane\'s Addiction, Soundgarden, and the Red Hot Chili Peppers toured together. "Alternative" became a tent big enough to hold contradictions — and for a moment, that tent was the mainstream.' },

  { type:'album', era:'slacker', year:1993, title:'Rid of Me', artist:'PJ Harvey', rating:5,
    tagline:'Power, rawness, and a feminist reckoning',
    art:'',
    artBg:'#1a0e14', artColor:'#c88090',
    tags:['Art rock','Feminist','Raw'],
    review:'Polly Jean Harvey dismantling every expectation about how women could sound in rock. Steve Albini recorded it like a field document — unflinching, uncomfortable, brilliant.',
    tracks:[{n:1,t:'Rid of Me',h:true},{n:2,t:'Missed',h:false},{n:3,t:'Legs',h:false},{n:4,t:'Rub \'Til It Bleeds',h:false},{n:5,t:'Hook',h:false},{n:6,t:'Man-Size Sextet',h:false},{n:7,t:'Highway \'61 Revisited',h:false},{n:8,t:'50ft Queenie',h:true},{n:9,t:'Yuri-G',h:false},{n:10,t:'Man-Size',h:true},{n:11,t:'Dry',h:false}],
    context:'Recorded in two weeks. Albini charged a flat fee. The album cost under $10,000.' },

  { type:'album', era:'slacker', year:1994, title:'Crooked Rain, Crooked Rain', artist:'Pavement', rating:5,
    tagline:'Lo-fi cool at its most seductive',
    art:'',
    artBg:'#1e1c0e', artColor:'#c0b860',
    tags:['Slacker','Lo-fi','College rock'],
    review:'The slacker manifesto. Stephen Malkmus wrote gorgeous pop melodies then immediately undermined them with wrong notes and elliptical lyrics. Nothing was trying too hard. Everything was perfect.',
    tracks:[{n:1,t:'Silence Kit',h:false},{n:2,t:'Elevate Me Later',h:true},{n:3,t:'Stop Breathin\'',h:false},{n:4,t:'Cut Your Hair',h:true},{n:5,t:'Newark Wilder',h:false},{n:6,t:'Unfair',h:false},{n:7,t:'Gold Soundz',h:true},{n:8,t:'5-4 = Unity',h:false},{n:9,t:'Range Life',h:true},{n:10,t:'Heaven Is a Truck',h:false},{n:11,t:'Hit the Plane Down',h:false}],
    context:'Pitchfork later named it one of the defining albums of the 1990s. At the time, it sold modestly on Matador Records.' },

  { type:'album', era:'slacker', year:1994, title:'In the Aeroplane Over the Sea', artist:'Neutral Milk Hotel', rating:5,
    tagline:'A basement cult object for the internet age',
    art:'',
    artBg:'#201408', artColor:'#d09060',
    tags:['Indie folk','Lo-fi','Avant-folk'],
    review:'Jeff Mangum recorded an album about Anne Frank in an Athens, Georgia basement. It barely sold at first. Then the internet happened, and it became the most obsessively discussed lo-fi album of its era — a genuine cult object.',
    tracks:[{n:1,t:'The King of Carrot Flowers Pt. 1',h:true},{n:2,t:'The King of Carrot Flowers Pts. 2 & 3',h:true},{n:3,t:'In the Aeroplane Over the Sea',h:true},{n:4,t:'Two-Headed Boy',h:true},{n:5,t:'The Fool',h:false},{n:6,t:'Holland, 1945',h:true},{n:7,t:'Communist Daughter',h:false},{n:8,t:'Oh Comely',h:true},{n:9,t:'Ghost',h:false},{n:10,t:'Untitled',h:false},{n:11,t:'Two-Headed Boy Pt. 2',h:true}],
    context:'Originally released on Merge Records in 1998. By the mid-2000s it had achieved legendary status on early music forums.' },

  // ─── BRITPOP ───
  { type:'album', era:'britpop', year:1994, title:'Parklife', artist:'Blur', rating:5,
    tagline:'England\'s suburban sociology, set to a groove',
    art:'',
    artBg:'#0e1828', artColor:'#5b8fd4',
    tags:['Britpop','British invasion','Concept'],
    review:'Damon Albarn\'s sociological survey of English suburban life — Phil Daniels narrating the title track while Albarn delivered the chorus. Every song a different character, a different Tuesday.',
    tracks:[{n:1,t:'Tracy Jacks',h:false},{n:2,t:'End of a Century',h:false},{n:3,t:'Parklife',h:true},{n:4,t:'Bank Holiday',h:false},{n:5,t:'Badhead',h:false},{n:6,t:'The Debt Collector',h:false},{n:7,t:'Far Out',h:false},{n:8,t:'To the End',h:true},{n:9,t:'London Loves',h:false},{n:10,t:'Trouble in the Message Centre',h:false},{n:11,t:'Girls & Boys',h:true}],
    context:'Won four Brit Awards in 1995, including Best British Album.' },

  { type:'album', era:'britpop', year:1995, title:'(What\'s the Story) Morning Glory?', artist:'Oasis', rating:4,
    tagline:'Anthems so big they collapsed Britpop under their weight',
    art:'',
    artBg:'#0c1420', artColor:'#4a7dc0',
    tags:['Britpop','Anthems','Stadium rock'],
    review:'The biggest album in Britain since The Beatles. Noel Gallagher\'s melodies were genuinely, almost annoyingly timeless. The attitude hasn\'t aged as well. The music very much has.',
    tracks:[{n:1,t:'Hello',h:false},{n:2,t:'Roll With It',h:false},{n:3,t:'Wonderwall',h:true},{n:4,t:'Don\'t Look Back in Anger',h:true},{n:5,t:'Hey Now!',h:false},{n:6,t:'The Masterplan',h:false},{n:7,t:'Some Might Say',h:true},{n:8,t:'Cast No Shadow',h:true},{n:9,t:'She\'s Electric',h:false},{n:10,t:'Morning Glory',h:true},{n:11,t:'Champagne Supernova',h:true}],
    context:'Sold 22 million copies worldwide. The Knebworth shows in 1996 drew 250,000 people over two nights.' },

  { type:'event', era:'britpop', year:1995,
    title:'"Country House" vs. "Roll With It" — the Battle of Britpop',
    eventType:'Cultural moment',
    body:'Blur and Oasis deliberately released singles on the same day. Blur won the chart battle. Oasis won the war. The moment crystallised a class and geography divide in British rock that still echoes.' },

  { type:'album', era:'britpop', year:1997, title:'OK Computer', artist:'Radiohead', rating:5,
    tagline:'Technology anxiety with orchestral scope',
    art:'',
    artBg:'#0e1018', artColor:'#8090c0',
    tags:['Art rock','Electronic','Post-Britpop'],
    review:'The album that ended Britpop by making it seem small. Thom Yorke wrote about alienation, technology anxiety, and road accidents with the scope of a classical composer. Jonny Greenwood\'s guitar had never sounded more like a horror film.',
    tracks:[{n:1,t:'Airbag',h:true},{n:2,t:'Paranoid Android',h:true},{n:3,t:'Subterranean Homesick Alien',h:false},{n:4,t:'Exit Music (For a Film)',h:true},{n:5,t:'Let Down',h:true},{n:6,t:'Karma Police',h:true},{n:7,t:'Fitter Happier',h:false},{n:8,t:'Electioneering',h:false},{n:9,t:'Climbing Up the Walls',h:false},{n:10,t:'No Surprises',h:true},{n:11,t:'Lucky',h:false},{n:12,t:'The Tourist',h:false}],
    context:'Named the greatest album of all time by multiple publications. At the time, the band considered abandoning it.' },

  { type:'album', era:'britpop', year:1998, title:'This Is Hardcore', artist:'Pulp', rating:5,
    tagline:'What happens the morning after the party',
    art:'',
    artBg:'#101428', artColor:'#6070b8',
    tags:['Britpop','Post-Britpop','Theatrical'],
    review:'Jarvis Cocker\'s hangover album — what happens after the party, when the glamour cracks and the morning comes. Britpop\'s most adult and most devastating statement. The title track is six minutes of dread.',
    tracks:[{n:1,t:'The Fear',h:true},{n:2,t:'Dishes',h:false},{n:3,t:'Help the Aged',h:true},{n:4,t:'This Is Hardcore',h:true},{n:5,t:'TV Movie',h:false},{n:6,t:'A Little Soul',h:true},{n:7,t:'I\'m a Man',h:false},{n:8,t:'Seductive Barry',h:false},{n:9,t:'Sylvia',h:false},{n:10,t:'Glory Days',h:false},{n:11,t:'The Day After the Revolution',h:false}],
    context:'Recorded after Jarvis Cocker was briefly detained by police at the 1996 Brit Awards for crashing Michael Jackson\'s performance.' },

  // ─── EMO ───
  { type:'album', era:'emo', year:2001, title:'Is This It', artist:'The Strokes', rating:5,
    tagline:'New York cool, delivered with a shrug',
    art:'',
    artBg:'#1a1010', artColor:'#c07070',
    tags:['Post-punk revival','New York','Cool'],
    review:'Five art school kids from New York made an album that sounded effortlessly like everything cool from 1977. Julian Casablancas sang like he\'d rather be anywhere else. Every song was a timed explosion.',
    tracks:[{n:1,t:'Is This It',h:true},{n:2,t:'The Modern Age',h:true},{n:3,t:'Soma',h:false},{n:4,t:'Barely Legal',h:false},{n:5,t:'Someday',h:true},{n:6,t:'Alone, Together',h:false},{n:7,t:'Last Nite',h:true},{n:8,t:'Hard to Explain',h:true},{n:9,t:'New York City Cops',h:false},{n:10,t:'Trying Your Luck',h:false},{n:11,t:'Take It or Leave It',h:false}],
    context:'Released September 2001. One week after 9/11. The New York City Cops track was pulled from the US version.' },

  { type:'event', era:'emo', year:2002,
    title:'The O.C. premieres — indie music enters prime time',
    eventType:'Crossover moment',
    body:'Fox\'s teen drama became the most reliable indie tastemaker on television. Music supervisor Alexandra Patsavas introduced Death Cab for Cutie, Modest Mouse, and Imogen Heap to millions. "What\'s the song?" became the show\'s secondary narrative.' },

  { type:'album', era:'emo', year:2003, title:'Three Cheers for Sweet Revenge', artist:'My Chemical Romance', rating:4,
    tagline:'Emo gets the theatrical heft it was always reaching for',
    art:'',
    artBg:'#200810', artColor:'#c45a8a',
    tags:['Emo','Theatrical','Rock opera'],
    review:'Gerard Way singing with the commitment of an opera singer trapped in a Halloween costume. The concept album structure gave the emo genre the theatrical heft it was always reaching for. Teenagers wept.',
    tracks:[{n:1,t:'Helena',h:true},{n:2,t:'The Ghost of You',h:true},{n:3,t:'I\'m Not Okay (I Promise)',h:true},{n:4,t:'Thank You for the Venom',h:true},{n:5,t:'I Never Told You What I Do for a Living',h:false},{n:6,t:'To the End',h:false},{n:7,t:'You Know What They Do to Guys Like Us in Prison',h:false},{n:8,t:'I\'m Not Okay (Acoustic)',h:false}],
    context:'Sold over a million copies in the US. Defined the Hot Topic era.' },

  { type:'album', era:'emo', year:2005, title:'Illinois', artist:'Sufjan Stevens', rating:5,
    tagline:'America\'s contradictions mapped across 22 movements',
    art:'',
    artBg:'#0e180e', artColor:'#70c070',
    tags:['Indie folk','Orchestral','Concept'],
    review:'A 22-track orchestral concept album about the state of Illinois. Sufjan Stevens somehow made it feel intimate. The opener is about a serial killer. The closer sounds like a hymn. In between: America at its most contradictory and beautiful.',
    tracks:[{n:1,t:'Concerning the UFO Sighting Near Highland, Illinois',h:true},{n:2,t:'The Black Hawk War',h:false},{n:3,t:'Come On! Feel the Illinoise!',h:true},{n:4,t:'John Wayne Gacy, Jr.',h:true},{n:5,t:'Jacksonville',h:false},{n:6,t:'Decatur',h:false},{n:7,t:'One Last "Whoo-Hoo!" for the Pullman',h:false},{n:8,t:'Chicago',h:true},{n:9,t:'Casimir Pulaski Day',h:true},{n:10,t:'To the Workers of the Rock River Valley Region',h:false}],
    context:'Part of a planned 50-state album project. Stevens has only completed two states.' },

  // ─── SLEAZE ───
  { type:'album', era:'sleaze', year:2007, title:'Neon Bible', artist:'Arcade Fire', rating:5,
    tagline:'Empire, dread, and anthems for the Bush era',
    art:'',
    artBg:'#1a1008', artColor:'#d4a040',
    tags:['Indie rock','Orchestral','Political'],
    review:'Where Funeral was about grief, Neon Bible was about dread — the dread of empire, of surveillance, of the church. Win Butler wrote anthems for the Bush era that felt genuinely apocalyptic without being preachy.',
    tracks:[{n:1,t:'Black Mirror',h:true},{n:2,t:'Keep the Car Running',h:true},{n:3,t:'Neon Bible',h:false},{n:4,t:'Intervention',h:true},{n:5,t:'Black Wave/Bad Vibrations',h:false},{n:6,t:'Ocean of Noise',h:true},{n:7,t:'The Well and the Lighthouse',h:false},{n:8,t:'(Antichrist Television Blues)',h:true},{n:9,t:'Windowsill',h:true},{n:10,t:'No Cars Go',h:true},{n:11,t:'My Body Is a Cage',h:true}],
    context:'Debuted at #2 in the US. Arcade Fire were now undeniably stadium-level — which created its own tensions.' },

  { type:'event', era:'sleaze', year:2008,
    title:'Arcade Fire win the Polaris Prize — indie goes mainstream',
    eventType:'Crossover moment',
    body:'Funeral\'s 2004 release had already redrawn the map, but the Grammy nomination and Polaris wins cemented it: indie rock could be both critically serious and commercially enormous. The term "indie" was quietly becoming meaningless.' },

  { type:'album', era:'sleaze', year:2008, title:'Vampire Weekend', artist:'Vampire Weekend', rating:4,
    tagline:'Graceland refracted through a prep school window',
    art:'',
    artBg:'#201808', artColor:'#d0a030',
    tags:['Indie pop','Afrobeat influence','Preppy'],
    review:'Paul Simon\'s Graceland refracted through a Columbia University dorm room. Ezra Koenig wrote about Oxford commas and Cape Cod kwassa kwassa with a breezy confidence that critics found insufferable and listeners found irresistible.',
    tracks:[{n:1,t:'Mansard Roof',h:false},{n:2,t:'Oxford Comma',h:true},{n:3,t:'A-Punk',h:true},{n:4,t:'Cape Cod Kwassa Kwassa',h:true},{n:5,t:'M79',h:true},{n:6,t:'Campus',h:false},{n:7,t:'Blake\'s Got a New Face',h:false},{n:8,t:'One (Blake\'s Got a New Face)',h:false},{n:9,t:'I Stand Corrected',h:false},{n:10,t:'Run',h:false},{n:11,t:'The Kids Don\'t Stand a Chance',h:false}],
    context:'Famously reviewed by Pitchfork with the observation that it was about "the upper-class college experience."' },

  { type:'album', era:'sleaze', year:2009, title:'Wolfgang Amadeus Phoenix', artist:'Phoenix', rating:5,
    tagline:'The festival summer\'s unofficial, undeniable soundtrack',
    art:'',
    artBg:'#1c1608', artColor:'#e0b830',
    tags:['Indie pop','French indie','Festival'],
    review:'Lisztomania became the unofficial theme song of every festival summer from 2009 to 2012. Phoenix made indie rock that was unashamedly fun — no irony, no distance, just perfect hooks delivered at perfect tempo.',
    tracks:[{n:1,t:'Lisztomania',h:true},{n:2,t:'1901',h:true},{n:3,t:'Fences',h:false},{n:4,t:'Love Like a Sunset Part I',h:false},{n:5,t:'Love Like a Sunset Part II',h:false},{n:6,t:'Lasso',h:false},{n:7,t:'Rome',h:true},{n:8,t:'Countdown',h:false},{n:9,t:'Girlfriend',h:true},{n:10,t:'Armistice',h:false}],
    context:'Won the Grammy for Best Alternative Album in 2010 — a first for a French band.' },

  { type:'event', era:'sleaze', year:2011,
    title:'Arcade Fire win Album of the Year at the Grammys',
    eventType:'Indie crossover milestone',
    body:'"Who is Arcade Fire?" trended on Twitter immediately after the announcement. An indie band on a small label beating Eminem and Katy Perry for the music industry\'s biggest prize. The indie establishment had arrived — and the underground moved on.' },

  { type:'album', era:'sleaze', year:2011, title:'Bon Iver', artist:'Bon Iver', rating:5,
    tagline:'Lo-fi solitude gives way to vast, synthetic landscapes',
    art:'',
    artBg:'#121818', artColor:'#70a8a0',
    tags:['Indie folk','Electronic','Orchestral'],
    review:'Justin Vernon followed his isolated cabin debut with something vast and synthetic. Bon Iver\'s self-titled abandoned the lo-fi aesthetic for orchestral electronics and Auto-Tune-as-instrument. It shouldn\'t have worked. It\'s one of the decade\'s best.',
    tracks:[{n:1,t:'Perth',h:true},{n:2,t:'Minnesota, WI',h:true},{n:3,t:'Holocene',h:true},{n:4,t:'Towers',h:false},{n:5,t:'Michicant',h:false},{n:6,t:'Hinnom, TX',h:false},{n:7,t:'Wash.',h:false},{n:8,t:'Calgary',h:true},{n:9,t:'Lisbon, OH',h:false},{n:10,t:'Beth/Rest',h:true}],
    context:'Debuted at #2 on the Billboard 200. Won Best New Artist at the Grammys the following year — Vernon publicly questioned whether the category was appropriate.' },

  // ─── BEDROOM ───
  { type:'album', era:'bedroom', year:2013, title:'Pure Heroine', artist:'Lorde', rating:5,
    tagline:'Sixteen years old, writing like a ten-year veteran',
    art:'',
    artBg:'#0a1018', artColor:'#6090c0',
    tags:['Bedroom pop','Minimalist','Coming-of-age'],
    review:'Ella Yelich-O\'Connor was 16 when she wrote about the psychological landscape of suburban adolescence with more precision than most adults achieve in a career. Joel Little\'s skeletal production gave her voice total authority.',
    tracks:[{n:1,t:'Tennis Court',h:true},{n:2,t:'400 Lux',h:false},{n:3,t:'Royals',h:true},{n:4,t:'Ribs',h:true},{n:5,t:'Buzzcut Season',h:true},{n:6,t:'Team',h:true},{n:7,t:'Glory and Gore',h:false},{n:8,t:'Still Sane',h:false},{n:9,t:'White Teeth Teens',h:false},{n:10,t:'A World Alone',h:true}],
    context:'"Royals" reached #1 in 26 countries. Became the first solo artist under 18 to top the Billboard Hot 100 since 1987.' },

  { type:'event', era:'bedroom', year:2013,
    title:'Beyoncé drops surprise self-titled album — the "surprise drop" era begins',
    eventType:'Industry shift',
    body:'At midnight on December 13th, 2013, Beyoncé released a visual album with no prior announcement. No singles, no marketing. It sold 828,773 copies in three days. The music industry\'s promotional model never fully recovered.' },

  { type:'album', era:'bedroom', year:2014, title:'Benji', artist:'Sun Kil Moon', rating:5,
    tagline:'Grief as stream-of-consciousness diary, guitar as witness',
    art:'',
    artBg:'#141008', artColor:'#c0a060',
    tags:['Indie folk','Confessional','Spoken word'],
    review:'Mark Kozelek abandoned conventional song structure for something closer to stream-of-consciousness diary entries set to fingerpicked guitar. Songs about friends dying, a Carissa White who survived a gas explosion. Grief as conversation.',
    tracks:[{n:1,t:'Carissa',h:true},{n:2,t:'I Watched the Film The Square and I Cried',h:false},{n:3,t:'Ben\'s My Friend',h:true},{n:4,t:'I Can\'t Live Without My Mother\'s Love',h:false},{n:5,t:'Pray for Newtown',h:true},{n:6,t:'Richard Ramirez Died Today of Natural Causes',h:false},{n:7,t:'Dog',h:false},{n:8,t:'Jim Wise',h:false},{n:9,t:'The Poseidon Adventure',h:false},{n:10,t:'Micheline',h:false}],
    context:'Created an entirely new critical conversation about narrative songwriting and the ethics of naming real people in songs.' },

  { type:'album', era:'bedroom', year:2017, title:'Antisocialites', artist:'Alvvays', rating:5,
    tagline:'Reverb, melancholy, and ten songs of inexplicable joy',
    art:'',
    artBg:'#0e0818', artColor:'#b060d0',
    tags:['Dream pop','Jangle','Indie pop'],
    review:'Molly Rankin writes hooks like the genre is dying and she\'s the only one who can save it. Antisocialites refined everything about Alvvays\' debut — the reverb, the melancholy, the inexplicable joy — and delivered ten near-perfect songs.',
    tracks:[{n:1,t:'In Undertow',h:true},{n:2,t:'Dreams Tonite',h:true},{n:3,t:'Already Gone',h:false},{n:4,t:'Your Type',h:true},{n:5,t:'Hey',h:false},{n:6,t:'Not My Baby',h:false},{n:7,t:'Plimsoll Punks',h:false},{n:8,t:'Saved by a Waif',h:false},{n:9,t:'Forget About Life',h:true},{n:10,t:'Caught on a Wave',h:false}],
    context:'Recorded and mixed in 11 days. Became one of the most critically acclaimed Canadian albums of the decade.' },

  { type:'album', era:'bedroom', year:2018, title:'Be the Cowboy', artist:'Mitski', rating:5,
    tagline:'Eleven songs about the densest, most articulate loneliness',
    art:'',
    artBg:'#180818', artColor:'#c060a0',
    tags:['Indie rock','Confessional','Art pop'],
    review:'Eleven songs, none longer than four minutes. Mitski writes about loneliness with the density of poetry and the directness of a text message. "Nobody" is the loneliest song about wanting to be touched since "Nightswimming."',
    tracks:[{n:1,t:'Geyser',h:true},{n:2,t:'Why Didn\'t You Stop Me?',h:false},{n:3,t:'Old Friend',h:false},{n:4,t:'A Pearl',h:false},{n:5,t:'Lonesome Love',h:true},{n:6,t:'Remember My Name',h:false},{n:7,t:'Me and My Husband',h:true},{n:8,t:'Come Into the Water',h:false},{n:9,t:'Nobody',h:true},{n:10,t:'Pink in the Night',h:true},{n:11,t:'A Horse Named Cold Air',h:false},{n:12,t:'Two Slow Dancers',h:true}],
    context:'Mitski announced her retirement from social media around this album\'s touring cycle, citing mental health. She came back.' },

  // ─── ALT-COUNTRY ───
  { type:'album', era:'altcountry', year:2019, title:'Better Oblivion Community Center', artist:'Better Oblivion Community Center', rating:4,
    tagline:'Two voices holding each other\'s uncertainty steady',
    art:'',
    artBg:'#18100a', artColor:'#c07840',
    tags:['Alt-country','Indie folk','Duo'],
    review:'Phoebe Bridgers and Conor Oberst make music that sounds like a long drive through a state you\'re not sure you believe in. The harmonies are the thing — two voices that find each other\'s uncertainty and hold it steady.',
    tracks:[{n:1,t:'Didn\'t Know What I Was in For',h:true},{n:2,t:'Dylan Thomas',h:true},{n:3,t:'My City',h:false},{n:4,t:'Chesapeake',h:false},{n:5,t:'Exception to the Rule',h:true},{n:6,t:'Service Road',h:false},{n:7,t:'Big Black Heart',h:false},{n:8,t:'Dominos',h:false},{n:9,t:'Forest Lawn',h:false},{n:10,t:'Salt and Lime',h:true}],
    context:'Surprise-released with no prior announcement, following the Beyoncé model.' },

  { type:'event', era:'altcountry', year:2020,
    title:'Phoebe Bridgers releases Punisher — pandemic as mirror',
    eventType:'Cultural moment',
    body:'Released during the first weeks of COVID lockdowns, Punisher became the album that articulated a specific kind of millennial grief — for intimacy, for certainty, for futures that weren\'t going to happen. "Funeral" had never been so literal.' },

  { type:'album', era:'altcountry', year:2021, title:'Promises', artist:'Floating Points, Pharoah Sanders & the LSO', rating:5,
    tagline:'Nine movements, one melodic fragment, infinite space',
    art:'',
    artBg:'#0a1410', artColor:'#60a878',
    tags:['Jazz','Ambient','Classical crossover'],
    review:'An 11-minute piece stretched across nine movements. Pharoah Sanders\' saxophone and Sam Shepherd\'s electronics and the London Symphony Orchestra all circling the same melodic fragment. The least indie album on this list. The most important.',
    tracks:[{n:1,t:'Movement 1',h:true},{n:2,t:'Movement 2',h:false},{n:3,t:'Movement 3',h:true},{n:4,t:'Movement 4',h:false},{n:5,t:'Movement 5',h:false},{n:6,t:'Movement 6',h:false},{n:7,t:'Movement 7',h:false},{n:8,t:'Movement 8',h:false},{n:9,t:'Movement 9',h:true}],
    context:'One of the few records on this list that will likely still be discussed in 50 years.' },

  { type:'album', era:'altcountry', year:2023, title:'GUTS', artist:'Olivia Rodrigo', rating:4,
    tagline:'Pop-punk hooks filtered through a major-label budget',
    art:'',
    artBg:'#180a1a', artColor:'#c060c0',
    tags:['Alt-pop','Gen Z','Post-poptimism'],
    review:'"Vampire" as a classic breakup song. "Bad Idea Right?" as the purest pop-punk hook since 2004. Rodrigo absorbed 30 years of indie influences, ran them through a major-label budget, and delivered the mainstream\'s most interesting album of 2023.',
    tracks:[{n:1,t:'vampire',h:true},{n:2,t:'bad idea right?',h:true},{n:3,t:'get him back!',h:true},{n:4,t:'lacy',h:true},{n:5,t:'ballad of a homeschooled girl',h:false},{n:6,t:'making the bed',h:false},{n:7,t:'teenage dream',h:true},{n:8,t:'pretty isn\'t pretty',h:false},{n:9,t:'the grudge',h:false},{n:10,t:'all-american bitch',h:true},{n:11,t:'logical',h:false},{n:12,t:'find a partner',h:false}],
    context:'Debuted at #1 in 17 countries. The day after release, "vampire" received 37 million streams.' },

  { type:'event', era:'altcountry', year:2024,
    title:'Beyoncé\'s Cowboy Carter and the mainstreaming of alt-country',
    eventType:'Crossover / genre-dissolution',
    body:'When the biggest pop star in the world makes a country album rooted in Black country music history, the indie/mainstream boundary dissolves. Cowboy Carter arrived as a political reclamation — pointing back to Charley Pride, Tina Turner, and Linda Martell.' },

  { type:'album', era:'altcountry', year:2024, title:'Manning Fireworks', artist:'MJ Lenderman', rating:5,
    tagline:'Slacker rock running clean into the present',
    art:'',
    artBg:'#181408', artColor:'#c0a040',
    tags:['Alt-country','Slacker rock','Guitar'],
    review:'The slacker rock tradition running clean into 2024. Lenderman plays guitar the way Pavement played guitar — slightly wrong, entirely right. Songs about nothing that feel like they\'re about everything. The lineage is intact.',
    tracks:[{n:1,t:'Joker Lips',h:true},{n:2,t:'Wristwatch',h:true},{n:3,t:'She\'s Leaving You',h:true},{n:4,t:'Bark at the Moon',h:false},{n:5,t:'On My Knees',h:false},{n:6,t:'Rudolph',h:false},{n:7,t:'You Don\'t Know the Shape I\'m In',h:false},{n:8,t:'Weird One',h:true},{n:9,t:'Donut Hole',h:false},{n:10,t:'Cell Phone Says',h:false}],
    context:'Released on ANTI- Records. The critical consensus was that Lenderman had made the year\'s best rock record with essentially no fuss at all.' },
];

const GENRES = {}; // { tagName: { desc: '' } }
const MOVEMENTS = []; // [{ id, era, label, desc }] — micromovements within eras
const SITE_CONFIG = {"kicker":"The Indie Current","titleHtml":"A <em>living</em><br>timeline","subtitle":"Albums, events, and cultural moments — the story of indie music's shifting centre of gravity, 1991 to now."};

